export default {
  LOGIN: 'AUTH/LOGIN',
  LOGIN_SUCCESS: 'AUTH/LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTH/LOGIN_FAILURE',
  REGISTER: 'AUTH/REGISTER',
  REGISTER_SUCCESS: 'AUTH/REGISTER_SUCCESS',
  REGISTER_FAILURE: 'AUTH/REGISTER_FAILURE',
  FETCH_USER_SUCCESS: 'AUTH/FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE: 'AUTH/FETCH_USER_FAILURE',
}
